documented server.ts ( still need to add more ) + added dummyHPC
cybergis/job-supervisor pull request #38
Opened 2022-05-31 02:00 UTC by mitkotak

create job with hpc == "dummy_hpc"

2022-05-31 02:23 UTC, mitkotak commented
@zimo-xiao Can you have a look at this PR ?

2022-05-31 16:11 UTC, zimo-xiao requested changes

2022-05-31 16:11 UTC, zimo-xiao commented on server.ts
> +            job.finishedAt = new Date()
Could you please help explain why would we want to end the job before submit? My understanding is that this is for testing only.

2022-05-31 16:11 UTC, zimo-xiao commented on configs/hpc.example.json
> +        "ip": "bridges2.psc.edu",
I would suggest you change the IP to the hpc's IP (in your case, the id of the docker container). Also, could you please add the key file as wekk as the docker-compose.yaml into the project? I could help you test the SSH functionality of the container.

2022-05-31 16:14 UTC, zimo-xiao commented on configs/hpc.example.json
> +        "ip": "bridges2.psc.edu",
My understanding was wrong. I though it was your dockerized HPC.

2022-05-31 16:15 UTC, zimo-xiao commented on server.ts
> +            job.finishedAt = new Date()
My understanding was wrong. I though it was your dockerized HPC.

2022-06-01 15:19 UTC, zimo-xiao commented
/lgtm

2022-06-01 15:19 UTC, merged

2022-06-02 04:16 UTC, mitkotak reviewed
Updated name + added sql query for job.finishedAt. Can you merge this commit as well