job sets finishedAt after completion
cybergis/job-supervisor pull request #84
Opened 2023-02-01 21:29 UTC by taylorziegler

Attempt to fix /statistic issue by resolving a bug in Supervisor.ts where the finishedAt field is not set for any jobs.

2023-03-29 20:57 UTC, taylorziegler commented
The issue was that we were using TIMESTAMPDIFF on a non-timestamp value in statistic.ts. I modified it to just be the difference in seconds.

2023-04-18 17:11 UTC, alexandermichels approved these changes
Looks fine, but please try to remove remove the exponential backoff code and put it in another branch/PR.

2023-04-18 17:11 UTC, alexandermichels commented on src/Supervisor.ts
> +        var ct = 1;
Can we remove this exponential backoff stuff from the PR and put it in another branch/PR?

2023-04-19 19:02 UTC, mitkotak requested changes
Good job ! Some minor nitpicks

2023-04-19 19:02 UTC, mitkotak commented on src/Supervisor.ts
> +
redundant space

2023-04-19 19:02 UTC, mitkotak commented on src/Statistic.ts
> +}
can you bring back the space

2023-04-19 19:02 UTC, mitkotak commented on src/Statistic.ts
> +
Is it helpful to default to null or something else in case there's any error ?

2023-04-19 20:24 UTC, alexandermichels approved these changes
LGTM

2023-04-19 20:34 UTC, mitkotak approved these changes
LGTM !

2023-04-19 20:34 UTC, merged